### ISSUE TITLE
Bad signal and unit question? 

### ISSUE THREAD

**Issue by PaginaRice** [Protocentral/protocentral_max30003#16]
Hello protocentral community,
I have been working on a project using the MAX30003 for several weeks now. Our signal is very unclear, (see attached image). Additionally, I am struggling to use the .csv file to troubleshoot because I don't know what the units are for the ecg data, and  the "timestamp" column is showing the same time for every single datapoint.

Does anyone have any insight on how to improve our signal and what the output data even means (units-wise)? Lastly, I noticed on the datasheet that it said filtering was an option, does that mean we have to opt to turn it on or off somewhere within the code? 

![helpimage](https://user-images.githubusercontent.com/38924877/39548925-e7c36592-4e10-11e8-84d3-9b1588d07a0b.JPG)

![helpimage2](https://user-images.githubusercontent.com/38924877/39549101-728fb694-4e11-11e8-941b-5c3802168261.JPG)

Any help would be greatly appreciated!
Thanks!

**Comment by adelalfusail** [comment]
there is some reasons you need to check:
 1-you need to make sure to pin connection 
2-you need to discharge computer from charger 
3-stay far from power source 60/120 HZ

**Comment by amir1994a** [comment]
@PaginaRice Hi, I'm facing the same problem for a long time! Have you been able to fix it?

**Comment by adelalfusail** [comment]
Can you explain more to understand your problem????

**Comment by joicetm** [comment]
are you able to fix it?
if not, you may try with the latest [commit](https://github.com/Protocentral/protocentral_max30003)

**Comment by joicetm** [comment]
Hi,
I am closing this issue for now, please feel free to open if its not fixed.
