### ISSUE TITLE
Sample Rate

### ISSUE THREAD

**Issue by Paulo1** [Protocentral/protocentral_max30003#22]
what's the maximum sampling rate for ECG data?

**Comment by joicetm** [comment]
Hi Paulo1,

Maximum sampling rate available is 512.

![Screenshot from 2021-06-09 09-48-26](https://user-images.githubusercontent.com/27211252/121292690-ffe3b800-c907-11eb-98a2-85b7471cbf65.png)

**Comment by Paulo1** [comment]
Thanks a lot.
