### ISSUE TITLE
Connection issue

### ISSUE THREAD

**Issue by matieu** [Protocentral/protocentral_max30003#24]
Hi,
I am trying to get a signal from the MAX30003. I followed the code example but I am stuck here: 

Serial.println("Failed to read ID, please make sure all the pins are connected");

I spent a few hours trying to debug this with not luck.

Please see my connections in the image. (I'm using the code sample from this repo)
-Am I doing something wrong?
-Is the card working? How can I test it?

I really want to make it work. Could please help me?

Many thanks!
![IMG_0046](https://user-images.githubusercontent.com/3856426/191849755-4b7c67fc-2db6-4acb-b947-a03d2475462f.jpg)

**Comment by MohammedHM** [comment]
Hi Matieu,

It appears that there is a contact issue between the header and the MAX30003 breakout board. Your interface between Arduino UNO and MAX30003 via breadboard is correct.

Can you solder the headers to the pins on the MAX30003 breakout board and try uploading the example code?

**Comment by matieu** [comment]
Indeed, it resolved the issue.

Thanks you so much!
