### ISSUE TITLE
Analog voltage differences 

### ISSUE THREAD

**Issue by fzldmn** [Protocentral/protocentral_max30003#4]
Hello in datasheet  recommended analog voltage is max 2V. 
But in your design u used 3.3V 

Will it be a problem for getting 
 stable measurements.

**Comment by VenkateshBhat** [comment]
Yes, the recommended power supply voltage is 1.1V - 2V , we tested for the long duration and there is no heating as such. We are getting the stable readings.

**Comment by DJMBurkhard** [comment]
Hello, 

1. Connecting the max30003 board with Arduino Uno: 
    Should I use the 3V or the 5V? 
    I assume it is one or the other? And the power is supplied via the computer (I am using a MAC)
   
2.   I cannot  upload the sketch to Arduino 
    I receive the message:
   fatal error: TimerOne.h: No such file or directory
   #include <TimerOne.h>

    Where can I find this file? It seems to be missing.

**Comment by VenkateshBhat** [comment]
@DJMBurkhard 
1. Connect to 5V if you are using Arduino Uno.
2. Install the library externally for TimerOne.h
Go to sketch->Include libray -> Manage libraries 
![libmanager](https://user-images.githubusercontent.com/6176131/30950388-2e05f2da-a43a-11e7-9c26-2894c3471a2b.JPG)
